services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pvt_app
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - APP_URL=http://localhost/pvt
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=pvt
      - DB_USERNAME=pvt_owner
      - DB_PASSWORD=OptiPlex3070
    volumes:
      - ./pvt2:/var/www/html/pvt2
    depends_on:
      - db
    networks:
      - pvt_network

  db:
    image: postgres:17
    container_name: pvt_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pvt
      - POSTGRES_USER=pvt_owner
      - POSTGRES_PASSWORD=OptiPlex3070
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pvt_clean.sql:/docker-entrypoint-initdb.d/backup.tar
      - ./restore-db.sh:/docker-entrypoint-initdb.d/restore-db.sh
    command: ["postgres", "-c", "max_connections=200", "-c", "shared_buffers=256MB"]
    networks:
      - pvt_network

networks:
  pvt_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 